In [4]:
import numpy as np
arr_zeros=np.zeros(10)
print(arr_zeros)
arr_zeros[4]=5
arr_zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [16]:
arr_h=[]
arr_h=np.arange(10,25,1)
a=np.sort(arr_h)[::-1]
print(a)

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_1=np.delete(arr_e,0)
arr_1

array([ 6,  1,  9, 10,  3, 27,  8,  6, 25, 16])

In [23]:
arr_3=np.append(arr_1,[10,20])
arr_3

array([ 6,  1,  9, 10,  3, 27,  8,  6, 25, 16, 10, 20])

In [24]:
arr_4=[]
arr_4=np.insert(arr_3,4,100)
arr_4

array([  6,   1,   9,  10, 100,   3,  27,   8,   6,  25,  16,  10,  20])

In [26]:
arr_5=np.delete(arr_4,[0,1,2])
arr_5

array([ 10, 100,   3,  27,   8,   6,  25,  16,  10,  20])